# 指定代码换行的长度
printWidth: 80
# tab缩进的空格数
tabWidth: 4
# 不使用 tab 缩进而是空格
useTabs: false
# 末尾是否添加分号
semi: false
# 使用单引号
singleQuote: true
# 在对象属性添加引号
quoteProps: 'as-needed'
# 在 jsx 中使用单引号而不是双引号
jsxSingleQuote: true
# 尾随逗号
trailingComma: 'none'
# 对象花括号和文本之间加空格
bracketSpacing: true
# 将多行标签元素的 > 放在最后一行的末尾，而不是单独放在下一行（不适用于自闭合元素）
bracketSameLine: true
# 在箭头函数参数周围加上括号
arrowParens: 'always'
# 指定 HTML文件的全局空白敏感性
htmlWhitespaceSensitivity: 'ignore'